#!/bin/bash

STYLES_DIR="$HOME/.config/hypr/styles"
CONFIG_DIR="$HOME/.config/hypr"
HYPR_CONF="$CONFIG_DIR/hyprland.conf"
WAYPAPER_CONF="$HOME/.config/waypaper/config.ini"
WALLPAPERS_DIR="$HOME/.config/Wallpapers"
WAYBAR_CONF_DIR="$HOME/.config/waybar"

styles=($(find "$STYLES_DIR" -maxdepth 1 -type d -printf "%f\n" | tail -n +2))

if [ ${#styles[@]} -eq 0 ]; then
    notify-send "Style Switcher" "No styles found" -t 3000
    exit 1
fi

selected=$(printf "%s\n" "${styles[@]}" | rofi -dmenu -p "Select style")

if [ -z "$selected" ] || [ ! -d "$STYLES_DIR/$selected" ]; then
    exit 0
fi

cp "$HYPR_CONF" "$HYPR_CONF.backup"

{
    echo "# Hyprland configuration - Style: $selected"
    echo "# Auto-generated by style switcher"
    echo ""

    echo "# Core configurations"
    for file in debug.conf devices.conf exec.conf general.conf input.conf look.conf misc.conf monitor.conf render.conf windowrules.conf binds.conf env.conf; do
        if [ -f "$STYLES_DIR/$selected/$file" ]; then
            echo "source = ~/.config/hypr/styles/$selected/$file"
        elif [ -f "$CONFIG_DIR/config/$file" ]; then
            echo "source = ~/.config/hypr/config/$file"
        fi
    done

    echo ""
    cat << 'EOF'
group {
    groupbar {
        font_family = JetBrains Mono
        font_size = 6
    }
}

debug {
    damage_blink = false
}
EOF

} > "$HYPR_CONF.new"

mv "$HYPR_CONF.new" "$HYPR_CONF"

if [ -f "$WAYPAPER_CONF" ]; then
    cp "$WAYPAPER_CONF" "$WAYPAPER_CONF.backup"

    wallpaper_path="$WALLPAPERS_DIR/$selected.png"

    if [ ! -f "$wallpaper_path" ]; then
        alternative_wallpaper=$(find "$WALLPAPERS_DIR" -type f -iname "*$selected*" | head -n 1)
        if [ -n "$alternative_wallpaper" ]; then
            wallpaper_path="$alternative_wallpaper"
        else
            wallpaper_path="$WALLPAPERS_DIR/background.png"
        fi
    fi

    sed -i "s|^folder = .*|folder = $WALLPAPERS_DIR|" "$WAYPAPER_CONF"
    sed -i "s|^wallpaper = .*|wallpaper = $wallpaper_path|" "$WAYPAPER_CONF"
    sed -i "s|^swww_transition_type = .*|swww_transition_type = wipe|" "$WAYPAPER_CONF"

    pkill waypaper
    #sleep 0.1
    waypaper --restore &
fi

if [ -d "$WAYBAR_CONF_DIR" ]; then
    waybar_style_css="$STYLES_DIR/$selected/waybar/style.css"

    if [ -f "$waybar_style_css" ]; then
        pkill waybar
        cp "$waybar_style_css" "$WAYBAR_CONF_DIR/style.css"
        #sleep 0.1
        waybar &
    fi
fi

notify-send "Style Switcher" "Applying $selected style..." -t 2000
#sleep 1
hyprctl reload

notify-send "Style Switcher" "Style '$selected' applied!" -t 3000
